### ISSUE TITLE
add generic PROJ.4 wrapper

### ISSUE THREAD

**Issue by gka** [kartograph/kartograph.py#34]
The idea is to add support for all projections included in [PROJ.4](http://trac.osgeo.org/proj/) by adding a generic wrapper projection:

``` yaml
proj:
  id: proj4
  opts: "+proj=moll"
```
