### ISSUE TITLE
Categorized styling

### ISSUE THREAD

**Issue by gka** [kartograph/kartograph.py#46]
As seen in QGis.

API proposal:

``` yaml
layers:
  - id: streets
    styles:
        categorized:
            column: highway
            attrs:
        motorway:
          stroke-weight: 2px
        primary:
          stroke-weight: 1px
```
